### ISSUE TITLE
Bug Redeploying the reverse proxy doesn't work as is.

### ISSUE THREAD

**Issue by brk114** [Azure/azure-iot-pcs-remote-monitoring-dotnet#106]
# Type of issue 
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description 
We are using a remote monitoring setup running in the Ubuntu 16.0 LTS azure vm, it was deployed through https://www.azureiotsolutions.com/.  

I want to add another dockerized api to the reverse proxy. I have updated the ngnix configuration and deployed it as a docker image. It didn't worked as is.  

So, I have tried to redeploy the the reverse-proxy solution as is from github without any modification, Then i observed this behavior that the solution is not working with my docker image.  
But it works with the image which comes as part of initial set up & the docker image from Initial setup.

I have observed few things, the ngnix runs on 10080, 10443 ports. the docker-compose.yml file has exposed with 443 & 80 ports.  
**nginx.conf**
```conf
    server {    
        listen              10080;    
        listen              10443 ssl;    
        ssl                   on;    
        server_name         reverseproxy 127.0.0.1;    
        ssl_certificate     /app/certs/tls.crt;    
        ssl_certificate_key /app/certs/tls.key;    
        ssl_protocols       TLSv1.2;    
        ....    
 } 
```  
Then i have mapped the 10080 port to 80 and 10443 to 443 in my docker-compose.yml file for reverse proxy.   
**docker-compose.yml (before modification)**
```yml
services:  
  reverseproxy:  
    image: azureiotpcs/remote-monitoring-nginx:1.0.0-preview.5  
    ports:  
      - "80:80"  
      - "443:443"  
    depends_on:  
      - webui
      - auth
      - iothubmanager
      - devicesimulation
      - telemetry
      - config
    volumes:
      - /app/certs:/app/certs:ro
```
**docker-compose.yml (after modification)**
```yml
services:
  reverseproxy:
    image: accountname/remote-monitoring-nginx:testing
    ports:
      - "80:10080"
      - "443:10443"
    depends_on:
      - webui
      - auth
      - iothubmanager
      - **customapi**
      - devicesimulation
      - telemetry
      - config
    volumes:
      - /app/certs:/app/certs:ro
```
Then the APIs worked as expected (including my custom api) but the remote monitoring UI is not working.  

Please suggest me the fix for this or suggest me a better way to do it.

# Screenshot 

# Steps to reproduce 
1. Have the remote monitoring solution deployed from https://www.azureiotsolutions.com/.
2. Create a reverse-proxy solution docker image from github remote monitoring PCS repository.
3. Push the image to docker hub.
4. Update the image in docker-compose.yml file.
5. Start the images with ./srtat.sh file.

# Expected behavior 
1. The solution should work as is with the ngnix configuration from github.

# Current behavior 
1. The reverse proxy solution is not working if we redeploy it from github code.

# Known workarounds 
* Updating the port mapping from 80 to 10080 and 443 to 10443. With this fix the APIs are working but the UI is not. 

# Possible solution 
...

# Context and Environment
* Operating System: Ubuntu LTS 16.0
* GitHub branch: latest reverse-proxy #99 
* .NET Runtime: .Net core 2.0
